#!/bin/sh

VERSION=0.1

basedir="$(dirname "$0")"
cd "$basedir"

cat header > A1_Necromancy
echo '' >> A1_Necromancy
cat base_scripts >> A1_Necromancy
for f in comp3Script/*; do
echo '' >> A1_Necromancy
cat $f >> A1_Necromancy
done
./espa -v A1_Necromancy || exit 1
touch -t 200606201200 A1_Necromancy.esp
#iconv -f UTF-8 -t CP1251 README | perl -p -e 's/\n/\r\n/' > Readme.txt
#iconv -f UTF-8 -t CP1251 VERSIONS | perl -p -e 's/\n/\r\n/' > Versions.txt
rm -rf A1_Necromancy_${VERSION}
rm -f A1_Necromancy_${VERSION}.zip
mkdir A1_Necromancy_${VERSION}
cp -a A1_Necromancy.esp A1_Necromancy_${VERSION}
#cp -a Screenshots Readme.txt Versions.txt A1_Alchemy_DaeCursed.esp A1_Alchemy_Potions.esp A1_Alchemy_V4_Containers.esp A1_Alchemy_V5_Apparatus.esp A1_Alchemy_V5_Apparatus_MFR.esp A1_Alchemy_${VERSION}
zip -v -X -9 -r A1_Necromancy_${VERSION}.zip A1_Necromancy_${VERSION} || exit 1
